{% set name = "dl1_data_handler" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dl1_data_handler-{{ version }}.tar.gz
  sha256: c157a05080108175ff670115987405ad1980cb34a7847e5c5341fa731a8ba160

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.20
    - scipy >=1.11
    - astropy
    - ctapipe ==0.21.2
    - traitlets >=5.0
    - jupyter
    - pandas
    - pytest-cov
    - pytables >=3.8

test:
  imports:
    - dl1_data_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/cta-observatory/dl1-data-handler
  summary: dl1 HDF5 data reader + processor
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcervinoucm
