{% set name = "dl1_data_handler" %}
{% set version = "0.14.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 89b5bfdffd01beaed048764d070207fe9b79b937d93bffb94d536c5608912690  # SHA256 from PyPI

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=65
    - setuptools_scm >=6.2
    - numpy
    - pandas
  run:
    - python >=3.12
    - ctapipe >=0.28
    - astropy
    - eventio
    - numpy
    - pandas
    - pip
    - pyyaml
    - scipy
    - traitlets
    - pydot
    - setuptools

test:
  imports:
    - dl1_data_handler
  commands:
    - pip check || true
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  summary: "Utilities for reading and processing CTA R1/DL0/DL1 data in a standardized format."
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rcervinoucm
